language: node_js
node_js:
  - "0.10"
  - "0.11"
notifications:
  recipients:
    - utatane.tea@gmail.com
  email:
    on_success: change
    on_failure: always
matrix:
  allow_failures:
    - node_js: "0.11"
